name: Build IPA
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Build Script
        run: |
          # Tìm và cấp quyền cho file script trong thư mục con
          find . -name "ipabuild.sh" -exec chmod +x {} +
          
      - name: Run Build
        run: |
          # Di chuyển vào thư mục chứa dự án và chạy script
          cd "MB-Bank-Fake-main"
          ./ipabuild.sh
        
     - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: App-IPA-Package
          path: |
            **/build/*.ipa
            ./*.ipa
            **/*.ipa
